options:
  smtp_connection_uri:
    description: SMTP connection URI
    type: string
    default: 'smtps://test:test@mailslurper:1025/?skip_ssl_verify=true'
  external_url:
    description:
      The URL under which Kratos is externally reachable (for example,
      if Kratos is served via a reverse proxy).
    type: string
    default: ""
  dev:
    description:
      Run Kratos on dev mode, it is needed if HTTPS is not set up. This should only be used for development purposes.
    type: boolean
    default: False
  login_ui_url:
    description: Kratos UI URL
    type: string
    default: "http://127.0.0.1:4455/"
  identity_schemas:
    description: A mapping of schema_id to identity schemas.
    type: string
  default_identity_schema:
    description: The default identity schema id, this option only works when `identity_schemas` is defined
    type: string
