options:
  smtp_connection_uri:
    description: SMTP connection URI
    type: string
    default: 'smtps://test:test@mailslurper:1025/?skip_ssl_verify=true'
  external_url:
    description:
      The URL under which Kratos is externally reachable (for example,
      if Kratos is served via a reverse proxy).
    type: string
    default: ""
