options:
  http_proxy:
    description: URL of the HTTP proxy eg http://proxy.internal:6666, it will set the HTTP_PROXY var in the workload environment
    type: string
    default: ''
  https_proxy:
    description: URL of the HTTPS proxy eg http://proxy.internal:6666, it will set the HTTPS_PROXY var in the workload environment
    type: string
    default: ''
  no_proxy:
    description: Domains that need to be excluded from proxying no_proxy="test.com,test.co.uk", it is a comma separate list
    type: string
    default: ''
  smtp_connection_uri:
    description: SMTP connection URI
    type: string
    default: 'smtps://test:test@mailslurper:1025/?skip_ssl_verify=true'
  dev:
    description:
      Run Kratos on dev mode, it is needed if HTTPS is not set up. This should only be used for development purposes.
    type: boolean
    default: False
  identity_schemas:
    description: |
      A mapping of schema_id to identity schemas. For example:
      {
        "user_v0": {
          "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
          "$schema": "http://json-schema.org/draft-07/schema#",
          "title": "Person",
          "type": "object",
          "properties": {
            "traits": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string",
                  "format": "email",
                  "title": "E-Mail",
                  "minLength": 3,
                  "ory.sh/kratos": {
                    "verification": {
                      "via": "email"
                    }
                  }
                },
                "name": {
                  "type": "string"
                }
              }
            },
            "additionalProperties": true
          }
        }
      }
    type: string
  default_identity_schema_id:
    description: The default identity schema id, this option only works when `identity_schemas` is defined
    type: string
  log_level:
    description: |
      The verbosity of logs produced by Kratos.
      Available values are: panic, fatal, error, warn, info, debug, and trace.
    type: string
    default: "info"
